INSERT INTO table_simple_cars (mileage, make, model, fuel, gear, offerType, price, hp, year) VALUES (235000, 'BMW', '316', 'Diesel', 'Manual', 'Used', 6800, 116, 2011);
INSERT INTO table_simple_cars (mileage, make, model, fuel, gear, offerType, price, hp, year) VALUES (92800, 'Volkswagen', 'Golf', 'Gasoline', 'Manual', 'Used', 6877, 122, 2011);
INSERT INTO table_simple_cars (mileage, make, model, fuel, gear, offerType, price, hp, year) VALUES (149300, 'SEAT', 'Exeo', 'Gasoline', 'Manual', 'Used', 6900, 160, 2011);
INSERT INTO table_simple_cars (mileage, make, model, fuel, gear, offerType, price, hp, year) VALUES (96200, 'Renault', 'Megane', 'Gasoline', 'Manual', 'Used', 6950, 110, 2011);
INSERT INTO table_simple_cars (mileage, make, model, fuel, gear, offerType, price, hp, year) VALUES (156000, 'Peugeot', '308', 'Gasoline', 'Manual', 'Used', 6950, 156, 2011);
INSERT INTO table_simple_cars (mileage, make, model, fuel, gear, offerType, price, hp, year) VALUES (147000, 'Toyota', 'Auris', 'Electric/Gasoline', 'Automatic', 'Used', 6950, 99, 2011);
INSERT INTO table_simple_cars (mileage, make, model, fuel, gear, offerType, price, hp, year) VALUES (91894, 'Renault', 'Scenic', 'Diesel', 'Manual', 'Used', 6970, 131, 2011);
INSERT INTO table_simple_cars (mileage, make, model, fuel, gear, offerType, price, hp, year) VALUES (127500, 'Opel', 'Zafira', 'Gasoline', 'Manual', 'Used', 6972, 116, 2011);
INSERT INTO table_simple_cars (mileage, make, model, fuel, gear, offerType, price, hp, year) VALUES (115000, 'Mazda', '3', 'Gasoline', 'Automatic', 'Used', 6980, 150, 2011);
INSERT INTO table_simple_cars (mileage, make, model, fuel, gear, offerType, price, hp, year) VALUES (104, 'Ford', 'Transit', 'Diesel', 'Manual', 'Used', 6990, 86, 2011);
INSERT INTO table_simple_cars (mileage, make, model, fuel, gear, offerType, price, hp, year) VALUES (59580, 'Opel', 'Meriva', 'Diesel', 'Automatic', 'Used', 6990, 101, 2011);
INSERT INTO table_simple_cars (mileage, make, model, fuel, gear, offerType, price, hp, year) VALUES (84000, 'Volkswagen', 'Golf', 'Gasoline', 'Manual', 'Used', 6990, 105, 2011);
INSERT INTO table_simple_cars (mileage, make, model, fuel, gear, offerType, price, hp, year) VALUES (427000, 'Mercedes-Benz', 'E 250', 'Diesel', 'Automatic', 'Used', 6990, 204, 2011);
INSERT INTO table_simple_cars (mileage, make, model, fuel, gear, offerType, price, hp, year) VALUES (109000, 'Chevrolet', 'Orlando', 'Gasoline', 'Manual', 'Used', 6990, 141, 2011);
INSERT INTO table_simple_cars (mileage, make, model, fuel, gear, offerType, price, hp, year) VALUES (194020, 'Audi', 'A4', 'Diesel', 'Manual', 'Used', 6999, 120, 2011);
INSERT INTO table_simple_cars (mileage, make, model, fuel, gear, offerType, price, hp, year) VALUES (72000, 'Volkswagen', 'Polo', 'Gasoline', 'Manual', 'Used', 6999, 60, 2011);
INSERT INTO table_simple_cars (mileage, make, model, fuel, gear, offerType, price, hp, year) VALUES (190000, 'Renault', 'Espace', 'Diesel', 'Manual', 'Used', 6999, 150, 2011);
INSERT INTO table_simple_cars (mileage, make, model, fuel, gear, offerType, price, hp, year) VALUES (190000, 'Renault', 'Grand Espace', 'Diesel', 'Manual', 'Used', 6999, 150, 2011);
INSERT INTO table_simple_cars (mileage, make, model, fuel, gear, offerType, price, hp, year) VALUES (85700, 'Fiat', 'Sedici', 'Diesel', 'Manual', 'Used', 6999, 135, 2011);
INSERT INTO table_simple_cars (mileage, make, model, fuel, gear, offerType, price, hp, year) VALUES (82000, 'Opel', 'Corsa', 'Gasoline', 'Manual', 'Used', 7000, 101, 2011);
INSERT INTO table_simple_cars (mileage, make, model, fuel, gear, offerType, price, hp, year) VALUES (44800, 'Kia', 'Picanto', 'Gasoline', 'Automatic', 'Used', 7850, 86, 2012);
INSERT INTO table_simple_cars (mileage, make, model, fuel, gear, offerType, price, hp, year) VALUES (81970, 'Volkswagen', 'Golf', 'Gasoline', 'Manual', 'Used', 7850, 105, 2012);
INSERT INTO table_simple_cars (mileage, make, model, fuel, gear, offerType, price, hp, year) VALUES (24000, 'Dacia', 'Duster', 'Gasoline', 'Manual', 'Used', 7900, 105, 2012);
INSERT INTO table_simple_cars (mileage, make, model, fuel, gear, offerType, price, hp, year) VALUES (193333, 'Volkswagen', 'Cross Touran', 'Diesel', 'Manual', 'Used', 7900, 105, 2012);
INSERT INTO table_simple_cars (mileage, make, model, fuel, gear, offerType, price, hp, year) VALUES (113000, 'Volkswagen', 'Beetle', 'Gasoline', 'Manual', 'Used', 7900, 105, 2012);
